version: '3.4'
networks:
  crudappnetwork:
services:
  databaseservice:
    container_name: postgresdbcontainer
    image: postgres:alpine
    ports:
      - 8002:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - crudappnetwork
  mvcwebservice:
    container_name: crudappcontainer
    image: siwatch/aspmvcapp:1.0
    ports:
      - 8001:80
    environment:
      - DB_HOST=databaseservice
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on: 
      - databaseservice
    networks:
      - crudappnetwork

