version: '3.4'
networks:
  demoblazorapp:
services:
  demoappdb:
    container_name: app-db
    image: postgres:alpine
    ports:
      - 8002:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - demoblazorapp
  mywebapp:
    container_name: my-web-app
    image: siwatch/crudmvcapp:1.0
    ports:
      - 8001:80
    environment:
      - DB_HOST=demoappdb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on: 
      - demoappdb
    networks:
      - demoblazorapp